
---
- hosts: webservers
  vars:
    ngx_port: 80
    ngx_name: www.bd.com
  tasks:
    - name: "关闭防火墙"
      systemd: name=firewalld state=stopped
    - name: "关闭selinux"
      shell: setenforce 0
    - name: "安装lnmp"
      yum: name={{ item }}  state=latest
      with_items:
        - mariadb
        - mariadb-server
        - php
        - php-mysql
        - php-fpm
        - gcc
        - pcre-devel
        - openssl-devel
    - name: "推送并解压nginx源码包"
      unarchive: src=nginx-1.18.0.tar.gz  dest=/root/
    - name: "检测编译安装nginx"
      shell: cd /root/nginx-1.18.0 && ./configure && make && make install
    - name: "开启nginx服务"
      shell: /usr/local/nginx/sbin/nginx || true
    - name: "开启php-fpm"
      systemd: name=php-fpm state=started enabled=yes
    - name: "推送PHP测试页面"
      copy: src=index.php  dest=/usr/local/nginx/html/index.php
    - name: "推送nginx配置文件"
      template: src=nginx.conf.j2  dest=/usr/local/nginx/conf/nginx.conf
      tags: restart_nginx
      notify: reload_nginx

  handlers:
    - name: reload_nginx
      shell: /usr/local/nginx/sbin/nginx -s reload
